resource "local_file" "pet" {
  filename = "/home/neron/Tutorials/Terraform/Terraform-Samples/TestFolder/08_pets.txt"
  content  = "My favourite pet is ${random_pet.my-pet.id}"
}

resource "random_pet" "my-pet" {
  prefix    = "Mrs"
  separator = "."
  length    = "1"
}

output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}